### ISSUE TITLE
Semver tags missing in Docker hub

### ISSUE THREAD

**Issue by clalbus** [Tecnativa/docker-tcp-proxy#3]
Could you, please, consider using semver tags alongside `latest` tag when pushing images to DockerHub?

We got bitten by the recent default timeout value change. This change would allow us to upgrade to newer versions in a controlled manner.

**Comment by Yajo** [comment]
Yikes, sorry about that!

I'll deploy 1.0.0 when #2 is merged. Is it good for you?

**Comment by clalbus** [comment]
Works for me, thanks!
